Backticks inside double-quotes are executed; need to escape them

diff --git a/tests/test-utils b/tests/test-utils
--- a/tests/test-utils
+++ b/tests/test-utils
@@ -86,6 +86,6 @@ print-binary-versions() {
     echo 'Versions:'
     local bin
     for bin in "${_TEST_BINARIES[@]}"; do
-        "$bin" --version || echo "`$bin --version` failed with status $?" >&2
+        "$bin" --version || echo "\`$bin --version\` failed with status $?" >&2
     done
 }
